spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cartest
    username: postgres
    password: "9462"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


image:
  upload:
    dir: /path/to/upload/directory